### ISSUE TITLE
Results of nnunet trainnig fold 0 with 10 subjects

### ISSUE THREAD

**Issue by WilliamSirois** [ivadomed/model-canal-seg#5]
# Données utilisées
J'ai utilisé la base de donnée spine generic dataset avec la version r20231212 sous la branche suivante, car il s'agit des images que Sandrine à du recentrer (pour positionner la segmentation au bon endroit) [images et segmentations utilisées](https://github.com/spine-generic/data-multi-subject.git) 
Update: you can you the following commands to get the 10 images:

```console
$ cd data-multi-subject
$ git checkout master
$ find . -name "*CSF*nii.gz"
./derivatives/labels/sub-barcelona05/anat/sub-barcelona05_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-nottwil03/anat/sub-nottwil03_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-nottwil04/anat/sub-nottwil04_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-geneva04/anat/sub-geneva04_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-tokyoIngenia06/anat/sub-tokyoIngenia06_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-pavia04/anat/sub-pavia04_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-perform02/anat/sub-perform02_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-cmrrb03/anat/sub-cmrrb03_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-tokyoIngenia05/anat/sub-tokyoIngenia05_T2w_label-CSF_seg.nii.gz
./derivatives/labels/sub-nottwil01/anat/sub-nottwil01_T2w_label-CSF_seg.nii.gz
```

# Commandes pour reproduire
1. Tout d'abord, j'ai utiliser le script de Jan pour convertir les données dans le format adéquat : 
[dataset conversion](https://github.com/ivadomed/utilities/blob/main/dataset_conversion/convert_bids_to_nnUNetV2.py)
2. J'ai ensuite fait une vérification de mes données avec la commande suivante : 
```
nnUNetv2_plan_and_preprocess -d 501 --verify_dataset_integrity -c  3d_fullres
```
3. J'ai ensuite été en mesure de démarrer l'entrainement avec la commande suivante (Durée de l'entrainement : 4,5 jours) : 
```
CUDA_VISIBLE_DEVICES=0 nnUNetv2_train 501 3d_fullres 0
```
4.J'ai ensuite procédé aux prédictions sur les deux images qui n'avaient pas été prises pour l'entrainement avec la commande suivante : 
```
nnUNetv2_predict -i ${nnUNet_raw}/Dataset501_MyDataset/imagesTs -o /home/williamsirois/testingmodel1 -d 501 -c 3d_fullres -f 0
```
5. Un coefficient dice à ensuite été calculer sur ces images en utilisant une variante du code qu'il est possible de trouver ici : [indice dice](https://gist.github.com/mingrui/5aa63ca498bbd615f932855c6a6dc724?fbclid=IwAR1XnFADBu2ZmiW0ERZQdxSe5R7MZhHzNlLn7dHSOKCc7d0Hp9zkDWP4IDg). J'ai adapter ce code pour qu'il soit possible de le faire pour plusieurs images à la suite, qu'il prennent des arguments en entrer et soit plus facile d'utilisation. 
# Résultats
## a) Entrainement
Voici les résultats de mon entrainement, on constate que le pseudo dice ne s'améliore pas une fois passé 250 epochs. Donc si il faut un second entrainement, je vais uniquement le faire sur 250 epochs.
![progress](https://github.com/ivadomed/model-csf-seg/assets/157057080/4a8dc272-ea62-4a63-a9fb-b09f6f0e7915)
## b) Images 
Voici les segmentation pour les deux sujets sur lesquels j'ai appliqué l'algorithme 
### nottwill04
Image : 
[MyDataset-sub-nottwil04_004_0000.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14502564/MyDataset-sub-nottwil04_004_0000.nii.gz) (Le nom n'est pas le même que dans la dataset j'ai repris l'image directement du serveur)
Segmentation : 
[sub-nottwil04_space-other_T2w_label-canal_seg.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14502575/sub-nottwil04_space-other_T2w_label-canal_seg.nii.gz)
Prédiction : 
[sub-nottwil04_T2w_label-canal_nnunet_seg.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14502623/sub-nottwil04_T2w_label-canal_nnunet_seg.nii.gz)
### tokyoIngenia05
Image : 
[MyDataset-sub-tokyoIngenia05_007_0000.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14502566/MyDataset-sub-tokyoIngenia05_007_0000.nii.gz) (Le nom n'est pas le même que dans la dataset j'ai repris l'image directement du serveur)
Segmentation : 
[sub-tokyoIngenia05_space-other_T2w_label-canal_seg.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14502573/sub-tokyoIngenia05_space-other_T2w_label-canal_seg.nii.gz)
Prédiction : 
[sub-tokyoIngenia05_T2w_label-canal_nnunet_seg.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14502621/sub-tokyoIngenia05_T2w_label-canal_nnunet_seg.nii.gz)
Il est possible de remarquer que la prédiction identifie le canal sur une région plus longue. C'est à dire que la prédiction se terminer plus haute que la segmentation que nous avons. Sinon, je n'ai pas remarqué de défauts majeurs. les prédictions sont très ressemblantes aux segmentations à quelques pixels près. 
## c) Score dice
Le score dice que j'ai calculé sont les suivant : 
* sujet nottwill04 : 0.9699
* sujet tokyoIngenia05 : 0.9599
Ce qui donne un score dice moyen de 0.9649
# Prochaine étape
Je vais ensuite lancer une prédiction sur le restant de la base de donnée et observer si le modèle est fiable pour des images qui ne font pas partie des 10 pour lesquels nous avons des segmentations.

**Comment by sandrinebedard** [comment]
C'est super les résultats, hâte de voir de quoi ça va avoir l'air sur la base de données entières!

N'oublie pas que tu dois utiliser les images dans `data-multi-subject/derivatives/data_preprocessed` pour l'appliquer!

**Comment by jcohenadad** [comment]
Bravo pour ces résultats @WilliamSirois 👏
En plus des suggestions de Sandrine https://github.com/ivadomed/model-csf-seg/issues/5#issuecomment-1983993907, pense à générer un QC report pour une évaluation plus aisée.

**Comment by WilliamSirois** [comment]
J'ai réalisé les prédictions sur l'ensemble des sujets de la base de donnée spine generic dataset avec la version r20231212 sous la branche suivante: [images et segmentations utilisées](https://github.com/spine-generic/data-multi-subject.git)
J'ai ensuite généré un QC report avec l'ensemble des sujets. Comme le fichier ZIP est trop volumineux pour pouvoir le mettre directement dans le Git hub, je l'ai mis dans le google drive de mon projet. Le fichier est disponible au lien suivant : [QC_report](https://drive.google.com/file/d/1cUDMfVCKsw91HgO5ijrXY5W-9Tm_Q9Xa/view?usp=drive_link)
Merci de m'indiquer si le lien fonctionne bien.
Aussi, je remarque que la segmentation générée présente des segmentation partielle en haut de la moelle épinière sur une grande partie des sujets. Je me demande si ces segmentations vont poser problème par la suite et s'il serait préférable de corriger les segmentations  et d'entrainer à nouveau l'algorithme pour tenter de corriger ce défaut.

**Comment by sandrinebedard** [comment]
> : [images et segmentations utilisées](https://github.com/spine-generic/data-multi-subject.git)

Ce lien me mène vers le master, tu voulais utiliser les images dans la branche [sb/156-add-preprocessed-images](https://github.com/spine-generic/data-multi-subject/tree/sb/156-add-preprocessed-images) sous `derivatives/derivatives/data_preprocessed` est-ce bien cela que tu as utilisé?

**Comment by sandrinebedard** [comment]
> Aussi, je remarque que la segmentation générée présente des segmentation partielle en haut de la moelle épinière sur une grande partie des sujets. Je me demande si ces segmentations vont poser problème par la suite et s'il serait préférable de corriger les segmentations et d'entrainer à nouveau l'algorithme pour tenter de corriger ce défaut.

Peux tu mettre un capture d'un exemple pour que l'on voit tu referes à quoi? 


Le lien fonctionne!

**Comment by sandrinebedard** [comment]
Les résultats sont supers @WilliamSirois ! Bravo 🎉 

> Aussi, je remarque que la segmentation générée présente des segmentation partielle en haut de la moelle épinière sur une grande partie des sujets. Je me demande si ces segmentations vont poser problème par la suite et s'il serait préférable de corriger les segmentations et d'entrainer à nouveau l'algorithme pour tenter de corriger ce défaut.

Je te conseille de tout simplement retirer ces slices (si c'est environ 2) au lieu de les corriger, on est plus dans le 
tronc cérébral à ce point que dans la moelle

**Comment by jcohenadad** [comment]
Super! Je remarque quelques trous, souvent dans la partie plus caudale, eg:
![Screenshot 2024-03-13 at 11 02 43 AM](https://github.com/ivadomed/model-csf-seg/assets/2482071/0b259e1a-63a5-4435-9ac1-2a61a2d7c739)

J'ai reviewé jusqu'à `sub-cmrrb06_space-other_T2w_0000.nii.gz` (pas le temps de reviewer plus), pour te faire une idée des sujets qui ont ce problème 👉  [qc_fail.yml.zip](https://github.com/ivadomed/model-csf-seg/files/14589663/qc_fail.yml.zip)

**Comment by WilliamSirois** [comment]
J'ai pris la prédiction de 20 sujets pour lesquels il y avait des problème (trous dans la segmentation ou segmentation non fermée) et j'ai corrigé la segmentation. J'ai ensuite réunis le tout dans un QC report qui est du format suivant : La segmentation corrigé du sujet 1, La prédiction du sujet 1 avant correction et ainsi de suite pour les 20 sujets.
Le QC report est disponible ici : [WS_QC_pred_corrige.zip](https://github.com/ivadomed/model-csf-seg/files/14625922/WS_QC_pred_corrige.zip)
Je vais ensuite prendre ces segmentations comme nouveaux groundtruth pour entrainer de nouveau mon algorithme. 
Merci de m'indiquer si certaines corrections que j'ai pus manquer sont encore nécessaire sur les sujets!

**Comment by jcohenadad** [comment]
> Merci de m'indiquer si certaines corrections que j'ai pus manquer sont encore nécessaire sur les sujets!

Ça me semble excellent-- good job!

**Comment by sandrinebedard** [comment]
C'est super @WilliamSirois ! Voici quelques corrections à faire, j'ai remarqué que souvent, tu sous-segmentes dans la direction droite-gauche (la forme de ta segmentation est ovale), voici quelques cas:

J'ai remarqué que pour le sujet `sub-oxfordFmrib04`, quelques slices avaient seulement la moitié de segmenté:

![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/694af8e8-ef74-4f8d-9c70-e58058662d39)


`sub-cardiff04`: les deux dernières slices sont sous segmentées
![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/eb23f884-f9d7-4763-b28b-57dc91823c3c)

`sub-cardiff01`: sous segmenté à la fin
![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/ee9d8fa3-b696-45e5-b01c-b7e8e50216c3)

`sub-balgrist04`: sous segmenté
![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/bf8435e6-c911-4e5c-9bc0-8ebcdaf28cc8)


`sub-cmrra03`
![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/a41b0ee5-0c42-4b81-8a66-afef9e7cd030)

`sub-mpicbs06`:
![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/fd480889-330c-4b8e-9543-7e6ea31363f8)

**Comment by WilliamSirois** [comment]
>C'est super @WilliamSirois ! Voici quelques corrections à faire, j'ai remarqué que souvent, tu sous-segmentes dans la direction droite-gauche (la forme de ta segmentation est ovale), voici quelques cas:

J'ai corrigé les segmentations dont tu m'as parlé et j'ai produit le nouveau QC report suivant :  
[WS_QC_pred_corrige.zip](https://github.com/ivadomed/model-csf-seg/files/14650764/WS_QC_pred_corrige.zip)
Pour ce qui est du  sujet `sub-oxfordFmrib04` , je crois que c'est dû au fait que la tranche est vraiment proche du bord donc elle ne s'affiche pas correctement dans le Qc report. Voici le fichier de l'image et sa segmentation.
[sub-oxfordFmrib04_space-other_T2w_026_0000.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14650748/sub-oxfordFmrib04_space-other_T2w_026_0000.nii.gz)
[sub-oxfordFmrib04_space-other_corrige_T2w_026.nii.gz](https://github.com/ivadomed/model-csf-seg/files/14650751/sub-oxfordFmrib04_space-other_corrige_T2w_026.nii.gz)
Je met aussi une photo pour montrer un exemple d'une des tranches problématique dans le Qc report mais qui semble bien dans la segmentation : 
![Image_oxford](https://github.com/ivadomed/model-csf-seg/assets/157057080/4d7a9149-2689-436d-81ff-1049db0f7ed4)

**Comment by jcohenadad** [comment]
I know you are only using the T2w, but I just wanted to mention that there are issues with that subject, which might or might not be related with your problem: https://github.com/spine-generic/data-multi-subject/blob/5398c0faf62b02e0475f76498a8af24c0c3722c2/exclude.yml#L11

**Comment by sandrinebedard** [comment]
J'ai regardé le QC et voici quelques slices encore à corriger:

Ce n'est pas une image évidente, il y a des artefacts dans le CSF, pour ça qu'il y a du noir, mais le canal doit l'inclure

![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/ef27e0db-86b3-480a-a594-d0107df708da)

Pour `sub-oxfordFmrib04`, en effet, c'est un problème d'affichage de QC, mais cette tranche est sous-segmentée:

La slice 3:
![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/3b13da5e-b4f2-4ee4-850c-201ef6f2a38f)


Ici aussi:

![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/4532bc5a-3522-4b45-be4d-f05f1bbbe440)

![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/92bd0a86-a49c-4001-92fc-253b2f5d9a3f)


Tu utilises ITK snap pour faire les corrections? Est-ce que tu augmentes le contraste et la luminosité lorsque tu fais ces corrections?

**Comment by WilliamSirois** [comment]
>Tu utilises ITK snap pour faire les corrections? Est-ce que tu augmentes le contraste et la luminosité lorsque tu fais ces corrections?

Oui j'utilise ITK snap pour faire les corrections et non je ne changeais pas le contraste et la luminosité, ce qui explique surement pourquoi je sous-segmentais!

J'ai apporter les corrections que tu m'as identifier j'espère avoir bien compris ce qu'il fallait pour le sujet `sub-strasbourg04`.

Voici donc le Qc report qui en découle : 
[WS_QC_pred_corrige.zip](https://github.com/ivadomed/model-csf-seg/files/14655015/WS_QC_pred_corrige.zip)

**Comment by sandrinebedard** [comment]
Il est important de changer le contraste/luminosité pour bien voir le contraste du canal spinal, surtout en bas de l'image, où il y a souvent une perte d'intensité. N'oublie pas que l'aspect important de la segmentation est sont contour qu'il corresponde bien à ton canal spinal.

Il te manque ici: 
![image](https://github.com/ivadomed/model-csf-seg/assets/71230552/708c1da2-f77f-4a93-993c-df78b60fe2db)


Le reste c'est bon 🎉 !

**Comment by WilliamSirois** [comment]
>Il te manque ici:

J'ai modifier les derniers détails dans le qc suivant : 
[WS_QC_pred_corrige.zip](https://github.com/ivadomed/model-csf-seg/files/14657979/WS_QC_pred_corrige.zip)

Pour entrainer je fais un nouvel algorithme ou si j'ajoute les images dans le dataset de mon premier algorithme et je l'entraine à nouveau?

**Comment by sandrinebedard** [comment]
> J'ai modifier les derniers détails dans le qc suivant : [WS_QC_pred_corrige.zip](https://github.com/ivadomed/model-csf-seg/files/14657979/WS_QC_pred_corrige.zip)_pred_corrige.zip)


C'est bon!


> Pour entrainer je fais un nouvel algorithme ou si j'ajoute les images dans le dataset de mon premier algorithme et je l'entraine à nouveau?

Oui, tu peux aussi me les envoyer, je vais les ajouter dans la base de données, je te conseille également de bien documenter les images (sujets) utilisé à chaque étape de ton active learning ainsi que le split!
